---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: defacement-detection
  labels:
    defacementComponent: mongodb
spec:
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    defacementComponent: mongodb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: defacement-detection
spec:
  selector:
    matchLabels:
      role: mongo
      environment: test
      defacementComponent: mongodb
  serviceName: "mongo"
  replicas: 3
  template:
    metadata:
      labels:
        role: mongo
        environment: test
        defacementComponent: mongodb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: mongo:4.2.3
        command: ["/bin/bash", "-c"]
        args:
          - mongod --replSet rs0 --port 27017 --bind_ip localhost,$(hostname -i) --oplogSize 128
        ports:
          - containerPort: 27017
        livenessProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - mongo --quiet --eval "db.getMongo()"
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - mongo --quiet --eval "db.getMongo()"
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
          - name: mongo-persistent-storage
            mountPath: /data/db
      - name: mongo-sidecar
        image: cvallance/mongo-k8s-sidecar
        env:
          - name: MONGO_SIDECAR_POD_LABELS
            value: "role=mongo,environment=test"
          - name: KUBE_NAMESPACE
            value: "defacement-detection"
  volumeClaimTemplates:
    - metadata:
        name: mongo-persistent-storage
      spec:
        storageClassName: "managed-nfs4k8s-storage"
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
---