---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-0
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/billy/persistent-volume/mongodb-0"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-0
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-0-service
  labels:
  run: mongodb-0-service
spec:
  ports:
  - port: 27017
  targetPort: 27017
  protocol: TCP
  selector:
  service: mongodb-0
---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb-0
  labels:
  env: test
  service: mongodb-0
spec:
  containers:
  - image: mtlbillyfong/mongodb-replica-set:20200330-stable-1
  name: mongodb-0
  resources:
    requests:
    ephemeral-storage: "2Gi"
    limits:
    ephemeral-storage: "4Gi"
  env:
  - name: "MONGO_INITDB_ROOT_USERNAME"
    value: "root"
  - name: "MONGO_INITDB_ROOT_PASSWORD"
    value: "example"
  - name: "MONGODB_ID"
    value: "mongo-0"
  livenessProbe:
    exec:
    command:
    - /bin/bash
    - -c
    - mongo --quiet --eval "db.getMongo()"
    initialDelaySeconds: 5
    periodSeconds: 5
  ports:
  - containerPort: 27017
  volumeMounts:
  - name: tz-hongkong
    mountPath: /etc/localtime
  - mountPath: "/data/db"
    name: mongodb-0-volume
  nodeSelector:
  # mongo-rs: all
  test-mongo-rs: rs0-0
  volumes:
  - name: tz-hongkong
  hostPath:
    path: /etc/localtime
  - name: mongodb-0-volume
  persistentVolumeClaim:
    claimName: mongodb-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-1
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/billy/persistent-volume/mongodb-1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-1
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-1-service
  labels:
  run: mongodb-1-service
spec:
  ports:
  - port: 27017
  targetPort: 27017
  protocol: TCP
  selector:
  service: mongodb-1
---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb-1
  labels:
  env: test
  service: mongodb-1
spec:
  containers:
  - image: mtlbillyfong/mongodb-replica-set:20200330-stable-1
  name: mongodb-1
  resources:
    requests:
    ephemeral-storage: "2Gi"
    limits:
    ephemeral-storage: "4Gi"
  env:
  - name: "MONGO_INITDB_ROOT_USERNAME"
    value: "root"
  - name: "MONGO_INITDB_ROOT_PASSWORD"
    value: "example"
  - name: "MONGODB_ID"
    value: "mongo-1"
  livenessProbe:
    exec:
    command:
    - /bin/bash
    - -c
    - mongo --eval "db.getMongo()"
    initialDelaySeconds: 5
    periodSeconds: 5

  ports:
  - containerPort: 27017
  volumeMounts:
  - name: tz-hongkong
    mountPath: /etc/localtime
  - mountPath: "/data/db"
    name: mongodb-1-volume
  nodeSelector:
  # mongo-rs: all
  test-mongo-rs: rs0-1
  volumes:
  - name: tz-hongkong
  hostPath:
    path: /etc/localtime
  - name: mongodb-1-volume
  persistentVolumeClaim:
    claimName: mongodb-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-2
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/billy/persistent-volume/mongodb-2"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-2
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-2-service
  labels:
  run: mongodb-2-service
spec:
  ports:
  - port: 27017
  targetPort: 27017
  protocol: TCP
  selector:
  service: mongodb-2
---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb-2
  labels:
  env: test
  service: mongodb-2
spec:
  containers:
  - image: mtlbillyfong/mongodb-replica-set:20200330-stable-1
  name: mongodb-2
  resources:
    requests:
    ephemeral-storage: "2Gi"
    limits:
    ephemeral-storage: "4Gi"
  env:
  - name: "MONGO_INITDB_ROOT_USERNAME"
    value: "root"
  - name: "MONGO_INITDB_ROOT_PASSWORD"
    value: "example"
  - name: "MONGODB_ID"
    value: "mongo-2"
  livenessProbe:
    exec:
    command:
    - /bin/bash
    - -c
    - mongo --quiet --eval "db.getMongo()"
    initialDelaySeconds: 5
    periodSeconds: 5

  ports:
  - containerPort: 27017
  volumeMounts:
  - name: tz-hongkong
    mountPath: /etc/localtime
  - mountPath: "/data/db"
    name: mongodb-2-volume
  nodeSelector:
  # mongo-rs: all
  test-mongo-rs: rs0-2
  volumes:
  - name: tz-hongkong
  hostPath:
    path: /etc/localtime
  - name: mongodb-2-volume
  persistentVolumeClaim:
    claimName: mongodb-2
---
